### PR TITLE
Bump detekt version

### PR DESCRIPTION
**Pull request by deejay1**
Upgrade detekt version and adapt config properly to only exclude test files on problematic rules as they were before, so any new infractions will be noticed.
Also implement some basic fixes with regard to new rules.

Merge after https://github.com/allegro/envoy-control/pull/175

### CODE REVIEW

**Review by pzmi — APPROVED** [review]
Lgtm

**Review by pzmi — DISMISSED** [review]

**Comment by deejay1** [comment]
Maybe I should do this as one PR with the upgrade?

**Review by lukidzi — APPROVED** [review]

**Comment by lukidzi** [comment]
@deejay1 Could you trigger a build?

**Comment by deejay1** [comment]
@lukidzi Sure, I was out of Internet range for a few days so I couldn't rerun it earlier...

**Review by lukidzi — APPROVED** [review]

**Review by pzmi — APPROVED** [review]

**Pull request merged**
